[package]
name = "the-project"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
twilight-gateway = "0.9"
twilight-http = "0.9"
twilight-model = "0.9"

[dependencies.tokio]
version = "1"
features = ["full"]
